from platform import python_version


print("Exercises - Day 1")
print("-----------------")
print()
print("Exercise: Level 1")
print("1. Check the python version you are using:", python_version())
print()
print("2. Open the python interactive shell and do the following operations. The operands are 3 and 4")
print("    Addition(+) = ", 3 + 4)
print("    Substraction(-) = ", 3 - 4)
print("    Multiplication(*) = ", 3 * 4)
print("    Modulus(%) = ", 3 % 4)
print("    Division(/) = ", 3 / 4)
print("    Exponential(**) = ", 3 ** 4)
print("    Floor Division Operator(//) = ", 3 // 4)
print()
print("3. Write strings on the python interactive shell. The strings are the following")
print("Your Name : ","Juan Alberto")
print("Your Family Name : ","González")
print("Your Country : ","Canary Islands")
print("I am enjoying 30 days of python")
print()
print("4. Check the data types of the following data")
print("type(10):", type(10))
print("type(9.8):", type(9.8))
print("type(3.14):", type(3.14))
print("type(4 - 4j):", type(4 - 4j))
print("type(['Asabeneh', 'Python', 'Finland']):", type(['Asabeneh', 'Python', 'Finland']))
print("type('Juan Alberto'):", type("Juan Alberto"))
print("type('González'):", type("González"))
print("type('Canary Islands'):", type("Canary Islands"))
print()
print()
print("Exercise: Level 2")
print("Create a folder named day_1 inside 30DaysOfPython folder. Inside day_1 folder, create a python file helloworld.py and repeat questions 1, 2, 3 and 4. Remember to use print() when you are working on a python file. Navigate to the directory where you have saved your file, and run it.")
print()
print()
print("Exercise: Level 3")
print("1. Write an example for different Python data types such as Number(Integer, Float, Complex), String, Boolean, List, Tuple, Set and Dictionary.")
print("    Integer", 8)
print("    Float", 8.2)
print("    Complex", (3 + 2j))
print("    String", "string")
print("    Boolean", False)
print("    List", [1,2,3])
print("    Tuple",(1,2,3))
print("    Set",{1,2,3})
print("    Dictionary",{1: 'One', 2: 'Two', 3: 'Three'})
print()
print("2. Find an Euclidian distance between (2, 3) and (10, 8)")
print(((10-2)**2+(8-3)**2)**0.5)
